# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/cr/projeto/task_53/task_53.tmp/FSMcommon_divisor.cache/wt [current_project]
set_property parent.project_path c:/cr/projeto/task_53/task_53.tmp/FSMcommon_divisor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  c:/CR/Projeto/Task_53/UserDefinedRepository
  c:/CR/Repositorio/Repository/Nexys4DispCont
  c:/CR/Repositorio/Repository/MemoryDisp2017
  c:/CR/Repositorio/Repository/FirstBlockDes2017
  c:/CR/Repositorio/Repository/BinToBCD2017
  c:/cr/projeto/task_53
} [current_project]
set_property ip_output_repo c:/cr/projeto/task_53/task_53.tmp/FSMcommon_divisor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib c:/CR/Projeto/Task_53/UserDefinedRepository/FSM_Common_Divisor/FSM_Common_Divisor.srcs/sources_1/new/FSM_Common_Divisor.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top FSM_max_common_divisor -part xc7a100tcsg324-3


write_checkpoint -force -noxdef FSM_max_common_divisor.dcp

catch { report_utilization -file FSM_max_common_divisor_utilization_synth.rpt -pb FSM_max_common_divisor_utilization_synth.pb }
