# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Task_53/Nexys4_Master.xdc

# Block Designs: bd/task_design_1/task_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1 || ORIG_REF_NAME==task_design_1}]

# IP: bd/task_design_1/ip/task_design_1_EightDispControl_0_0/task_design_1_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_EightDispControl_0_0 || ORIG_REF_NAME==task_design_1_EightDispControl_0_0}]

# IP: bd/task_design_1/ip/task_design_1_blk_mem_gen_0_0/task_design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==task_design_1_blk_mem_gen_0_0}]

# IP: bd/task_design_1/ip/task_design_1_xlconstant_1_0/task_design_1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlconstant_1_0 || ORIG_REF_NAME==task_design_1_xlconstant_1_0}]

# IP: bd/task_design_1/ip/task_design_1_blk_mem_gen_1_1/task_design_1_blk_mem_gen_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_blk_mem_gen_1_1 || ORIG_REF_NAME==task_design_1_blk_mem_gen_1_1}]

# IP: bd/task_design_1/ip/task_design_1_microblaze_0_0/task_design_1_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_microblaze_0_0 || ORIG_REF_NAME==task_design_1_microblaze_0_0}]

# IP: bd/task_design_1/ip/task_design_1_dlmb_v10_0/task_design_1_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_dlmb_v10_0 || ORIG_REF_NAME==task_design_1_dlmb_v10_0}]

# IP: bd/task_design_1/ip/task_design_1_ilmb_v10_0/task_design_1_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_ilmb_v10_0 || ORIG_REF_NAME==task_design_1_ilmb_v10_0}]

# IP: bd/task_design_1/ip/task_design_1_dlmb_bram_if_cntlr_0/task_design_1_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==task_design_1_dlmb_bram_if_cntlr_0}]

# IP: bd/task_design_1/ip/task_design_1_ilmb_bram_if_cntlr_0/task_design_1_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==task_design_1_ilmb_bram_if_cntlr_0}]

# IP: bd/task_design_1/ip/task_design_1_lmb_bram_0/task_design_1_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_lmb_bram_0 || ORIG_REF_NAME==task_design_1_lmb_bram_0}]

# IP: bd/task_design_1/ip/task_design_1_microblaze_0_axi_periph_0/task_design_1_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==task_design_1_microblaze_0_axi_periph_0}]

# IP: bd/task_design_1/ip/task_design_1_mdm_1_0/task_design_1_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_mdm_1_0 || ORIG_REF_NAME==task_design_1_mdm_1_0}]

# IP: bd/task_design_1/ip/task_design_1_clk_wiz_1_0/task_design_1_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_clk_wiz_1_0 || ORIG_REF_NAME==task_design_1_clk_wiz_1_0}]

# IP: bd/task_design_1/ip/task_design_1_rst_clk_wiz_1_100M_0/task_design_1_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==task_design_1_rst_clk_wiz_1_100M_0}]

# IP: bd/task_design_1/ip/task_design_1_axi_gpio_0_0/task_design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_axi_gpio_0_0 || ORIG_REF_NAME==task_design_1_axi_gpio_0_0}]

# IP: bd/task_design_1/ip/task_design_1_xbar_0/task_design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xbar_0 || ORIG_REF_NAME==task_design_1_xbar_0}]

# IP: bd/task_design_1/ip/task_design_1_xlslice_0_0/task_design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlslice_0_0 || ORIG_REF_NAME==task_design_1_xlslice_0_0}]

# IP: bd/task_design_1/ip/task_design_1_xlconstant_2_0/task_design_1_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlconstant_2_0 || ORIG_REF_NAME==task_design_1_xlconstant_2_0}]

# IP: bd/task_design_1/ip/task_design_1_xlslice_1_0/task_design_1_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlslice_1_0 || ORIG_REF_NAME==task_design_1_xlslice_1_0}]

# IP: bd/task_design_1/ip/task_design_1_xlconstant_3_0/task_design_1_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlconstant_3_0 || ORIG_REF_NAME==task_design_1_xlconstant_3_0}]

# IP: bd/task_design_1/ip/task_design_1_xlslice_2_0/task_design_1_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlslice_2_0 || ORIG_REF_NAME==task_design_1_xlslice_2_0}]

# IP: bd/task_design_1/ip/task_design_1_xlslice_3_0/task_design_1_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlslice_3_0 || ORIG_REF_NAME==task_design_1_xlslice_3_0}]

# IP: bd/task_design_1/ip/task_design_1_xlslice_4_0/task_design_1_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlslice_4_0 || ORIG_REF_NAME==task_design_1_xlslice_4_0}]

# IP: bd/task_design_1/ip/task_design_1_xlconcat_1_0/task_design_1_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlconcat_1_0 || ORIG_REF_NAME==task_design_1_xlconcat_1_0}]

# IP: bd/task_design_1/ip/task_design_1_xlslice_5_0/task_design_1_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlslice_5_0 || ORIG_REF_NAME==task_design_1_xlslice_5_0}]

# IP: bd/task_design_1/ip/task_design_1_xlconcat_2_0/task_design_1_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlconcat_2_0 || ORIG_REF_NAME==task_design_1_xlconcat_2_0}]

# IP: bd/task_design_1/ip/task_design_1_xlslice_6_0/task_design_1_xlslice_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlslice_6_0 || ORIG_REF_NAME==task_design_1_xlslice_6_0}]

# IP: bd/task_design_1/ip/task_design_1_xlslice_7_0/task_design_1_xlslice_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlslice_7_0 || ORIG_REF_NAME==task_design_1_xlslice_7_0}]

# IP: bd/task_design_1/ip/task_design_1_xlslice_8_0/task_design_1_xlslice_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlslice_8_0 || ORIG_REF_NAME==task_design_1_xlslice_8_0}]

# IP: bd/task_design_1/ip/task_design_1_xlslice_9_0/task_design_1_xlslice_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlslice_9_0 || ORIG_REF_NAME==task_design_1_xlslice_9_0}]

# IP: bd/task_design_1/ip/task_design_1_unroll_0_0/task_design_1_unroll_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_unroll_0_0 || ORIG_REF_NAME==task_design_1_unroll_0_0}]

# IP: bd/task_design_1/ip/task_design_1_VGA_for_block_0_0/task_design_1_VGA_for_block_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_VGA_for_block_0_0 || ORIG_REF_NAME==task_design_1_VGA_for_block_0_0}]

# IP: bd/task_design_1/ip/task_design_1_xlslice_10_0/task_design_1_xlslice_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlslice_10_0 || ORIG_REF_NAME==task_design_1_xlslice_10_0}]

# IP: bd/task_design_1/ip/task_design_1_xlslice_11_0/task_design_1_xlslice_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlslice_11_0 || ORIG_REF_NAME==task_design_1_xlslice_11_0}]

# IP: bd/task_design_1/ip/task_design_1_xlconstant_0_0/task_design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlconstant_0_0 || ORIG_REF_NAME==task_design_1_xlconstant_0_0}]

# IP: bd/task_design_1/ip/task_design_1_xlconcat_0_0/task_design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_xlconcat_0_0 || ORIG_REF_NAME==task_design_1_xlconcat_0_0}]

# IP: bd/task_design_1/ip/task_design_1_FSM_max_common_divisor_0_0/task_design_1_FSM_max_common_divisor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==task_design_1_FSM_max_common_divisor_0_0 || ORIG_REF_NAME==task_design_1_FSM_max_common_divisor_0_0}]

# XDC: bd/task_design_1/ip/task_design_1_blk_mem_gen_0_0/task_design_1_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/task_design_1/ip/task_design_1_blk_mem_gen_1_1/task_design_1_blk_mem_gen_1_1_ooc.xdc

# XDC: bd/task_design_1/ip/task_design_1_microblaze_0_0/task_design_1_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==task_design_1_microblaze_0_0 || ORIG_REF_NAME==task_design_1_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/task_design_1/ip/task_design_1_microblaze_0_0/task_design_1_microblaze_0_0_ooc_debug.xdc

# XDC: bd/task_design_1/ip/task_design_1_microblaze_0_0/task_design_1_microblaze_0_0_ooc.xdc

# XDC: bd/task_design_1/ip/task_design_1_dlmb_v10_0/task_design_1_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==task_design_1_dlmb_v10_0 || ORIG_REF_NAME==task_design_1_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/task_design_1/ip/task_design_1_dlmb_v10_0/task_design_1_dlmb_v10_0_ooc.xdc

# XDC: bd/task_design_1/ip/task_design_1_ilmb_v10_0/task_design_1_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==task_design_1_ilmb_v10_0 || ORIG_REF_NAME==task_design_1_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/task_design_1/ip/task_design_1_ilmb_v10_0/task_design_1_ilmb_v10_0_ooc.xdc

# XDC: bd/task_design_1/ip/task_design_1_dlmb_bram_if_cntlr_0/task_design_1_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/task_design_1/ip/task_design_1_ilmb_bram_if_cntlr_0/task_design_1_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/task_design_1/ip/task_design_1_lmb_bram_0/task_design_1_lmb_bram_0_ooc.xdc

# XDC: bd/task_design_1/ip/task_design_1_mdm_1_0/task_design_1_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==task_design_1_mdm_1_0 || ORIG_REF_NAME==task_design_1_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/task_design_1/ip/task_design_1_mdm_1_0/task_design_1_mdm_1_0_ooc_trace.xdc

# XDC: bd/task_design_1/ip/task_design_1_mdm_1_0/task_design_1_mdm_1_0_ooc.xdc

# XDC: bd/task_design_1/ip/task_design_1_clk_wiz_1_0/task_design_1_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==task_design_1_clk_wiz_1_0 || ORIG_REF_NAME==task_design_1_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/task_design_1/ip/task_design_1_clk_wiz_1_0/task_design_1_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==task_design_1_clk_wiz_1_0 || ORIG_REF_NAME==task_design_1_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/task_design_1/ip/task_design_1_clk_wiz_1_0/task_design_1_clk_wiz_1_0_ooc.xdc

# XDC: bd/task_design_1/ip/task_design_1_rst_clk_wiz_1_100M_0/task_design_1_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==task_design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==task_design_1_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/task_design_1/ip/task_design_1_rst_clk_wiz_1_100M_0/task_design_1_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==task_design_1_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==task_design_1_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/task_design_1/ip/task_design_1_rst_clk_wiz_1_100M_0/task_design_1_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/task_design_1/ip/task_design_1_axi_gpio_0_0/task_design_1_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==task_design_1_axi_gpio_0_0 || ORIG_REF_NAME==task_design_1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/task_design_1/ip/task_design_1_axi_gpio_0_0/task_design_1_axi_gpio_0_0_ooc.xdc

# XDC: bd/task_design_1/ip/task_design_1_axi_gpio_0_0/task_design_1_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==task_design_1_axi_gpio_0_0 || ORIG_REF_NAME==task_design_1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/task_design_1/ip/task_design_1_xbar_0/task_design_1_xbar_0_ooc.xdc

# XDC: bd/task_design_1/task_design_1_ooc.xdc
