# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/CR/Projeto/Task_53/Task_53.cache/wt [current_project]
set_property parent.project_path C:/CR/Projeto/Task_53/Task_53.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  c:/CR/Projeto/Task_53/UserDefinedRepository
  c:/CR/Repositorio/Repository/Nexys4DispCont
  c:/CR/Repositorio/Repository/MemoryDisp2017
  c:/CR/Repositorio/Repository/FirstBlockDes2017
  c:/CR/Repositorio/Repository/BinToBCD2017
  c:/cr/projeto/task_53
} [current_project]
set_property ip_output_repo c:/CR/Projeto/Task_53/Task_53.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/hdl/task_design_1_wrapper.vhd
add_files C:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/task_design_1.bd
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_blk_mem_gen_0_0/task_design_1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_blk_mem_gen_1_1/task_design_1_blk_mem_gen_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_microblaze_0_0/task_design_1_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_microblaze_0_0/task_design_1_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_microblaze_0_0/task_design_1_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_dlmb_v10_0/task_design_1_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_dlmb_v10_0/task_design_1_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_ilmb_v10_0/task_design_1_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_ilmb_v10_0/task_design_1_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_dlmb_bram_if_cntlr_0/task_design_1_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_ilmb_bram_if_cntlr_0/task_design_1_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_lmb_bram_0/task_design_1_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_mdm_1_0/task_design_1_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_mdm_1_0/task_design_1_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_mdm_1_0/task_design_1_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_clk_wiz_1_0/task_design_1_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_clk_wiz_1_0/task_design_1_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_clk_wiz_1_0/task_design_1_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_rst_clk_wiz_1_100M_0/task_design_1_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_rst_clk_wiz_1_100M_0/task_design_1_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_rst_clk_wiz_1_100M_0/task_design_1_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_axi_gpio_0_0/task_design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_axi_gpio_0_0/task_design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_axi_gpio_0_0/task_design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/ip/task_design_1_xbar_0/task_design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/task_design_1_ooc.xdc]
set_property is_locked true [get_files C:/CR/Projeto/Task_53/Task_53.srcs/sources_1/bd/task_design_1/task_design_1.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/CR/Projeto/Task_53/Task_53.srcs/constrs_1/imports/Task_53/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/CR/Projeto/Task_53/Task_53.srcs/constrs_1/imports/Task_53/Nexys4_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top task_design_1_wrapper -part xc7a100tcsg324-3


write_checkpoint -force -noxdef task_design_1_wrapper.dcp

catch { report_utilization -file task_design_1_wrapper_utilization_synth.rpt -pb task_design_1_wrapper_utilization_synth.pb }
