# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/CR/Projeto/Task_53/UserDefinedRepository/Unroll/Unroll.cache/wt [current_project]
set_property parent.project_path C:/CR/Projeto/Task_53/UserDefinedRepository/Unroll/Unroll.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/CR/Projeto/Task_53/UserDefinedRepository/Unroll/Unroll.srcs/sources_1/new [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib C:/CR/Projeto/Task_53/UserDefinedRepository/Unroll/Unroll.srcs/sources_1/new/TopUnroll.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Unroll_ROM_last -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Unroll_ROM_last.dcp

catch { report_utilization -file Unroll_ROM_last_utilization_synth.rpt -pb Unroll_ROM_last_utilization_synth.pb }
