# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/CR/Projeto/Task_53/UserDefinedRepository/compVGA/compVGA.cache/wt [current_project]
set_property parent.project_path C:/CR/Projeto/Task_53/UserDefinedRepository/compVGA/compVGA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/CR/Projeto/Task_53/UserDefinedRepository/compVGA/compVGA.srcs/sources_1/imports/zedboardsorter4 [current_project]
set_property ip_output_repo c:/CR/Projeto/Task_53/UserDefinedRepository/compVGA/compVGA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/CR/Projeto/Task_53/UserDefinedRepository/compVGA/compVGA.srcs/sources_1/imports/ZedBoardSorter4/Monitor.vhd
  C:/CR/Projeto/Task_53/UserDefinedRepository/compVGA/compVGA.srcs/sources_1/imports/ZedBoardSorter4/Clock_divider.vhd
  C:/CR/Projeto/Task_53/UserDefinedRepository/compVGA/compVGA.srcs/sources_1/imports/ZedBoardSorter4/RAM.vhd
  C:/CR/Projeto/Task_53/UserDefinedRepository/compVGA/compVGA.srcs/sources_1/imports/ZedBoardSorter4/RGBMux.vhd
  C:/CR/Projeto/Task_53/UserDefinedRepository/compVGA/compVGA.srcs/sources_1/imports/ZedBoardSorter4/SymbolROM.vhdl
  C:/CR/Projeto/Task_53/UserDefinedRepository/compVGA/compVGA.srcs/sources_1/imports/ZedBoardSorter4/VGATileMatrix.vhd
  C:/CR/Projeto/Task_53/UserDefinedRepository/compVGA/compVGA.srcs/sources_1/imports/ZedBoardSorter4/VGASync.vhd
  C:/CR/Projeto/Task_53/UserDefinedRepository/compVGA/compVGA.srcs/sources_1/imports/ZedBoardSorter4/TopLevelVGA.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top VGA_for_block -part xc7a100tcsg324-1


write_checkpoint -force -noxdef VGA_for_block.dcp

catch { report_utilization -file VGA_for_block_utilization_synth.rpt -pb VGA_for_block_utilization_synth.pb }
